package com.ham.music_buttomBlock;

import android.util.Log;

import androidx.annotation.NonNull;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.lang.reflect.Constructor;
import java.lang.reflect.Field;
import java.lang.reflect.Method;
import java.util.ArrayList;
import java.util.List;

import io.github.libxposed.api.XposedInterface;
import io.github.libxposed.api.XposedModule;
import io.github.libxposed.api.XposedModuleInterface;

/**
 * LSPosed module: disable custom media buttons (custom0/custom1)
 * for configured apps in MIUI/HyperOS SystemUI notification bar / media island controls.
 *
 * <p>Background: MIUI SystemUI media controls have 5 button slots:
 * action0=custom0, action1=prev, action2=play/pause, action3=next, action4=custom1.
 * custom0/custom1 come from MediaSession PlaybackState.getCustomActions(),
 * generated by MediaActionsKt.createActionsFromState().
 *
 * <p>This module hooks createActionsFromState and, when the package is in the
 * blocked list, clears the two custom buttons so they do not appear in the
 * notification media controls.
 */
public final class ModuleMain extends XposedModule {
    private static final String TAG = "MusicButtonBlock";
    private static final String HOOK_TARGET_CLASS =
            "com.android.systemui.media.controls.domain.pipeline.MediaActionsKt";

    // Config file path (must match ConfigManager.HOOK_CONFIG_FILE)
    private static final String CONFIG_FILE =
            "/data/user_de/0/com.ham.music_buttomBlock/files/blocked_packages.txt";
    private static final String[] DEFAULT_PACKAGES = {
            "com.netease.cloudmusic",
            "com.tencent.qqmusic"
    };

    private volatile boolean installed;
    private volatile List<String> blockedPackages;

    public ModuleMain() {
        super();
    }

    @Override
    public void onModuleLoaded(@NonNull XposedModuleInterface.ModuleLoadedParam param) {
        log(Log.INFO, TAG, "event=module_loaded process=" + param.getProcessName()
                + " api=" + getApiVersion()
                + " framework=" + getFrameworkName()
                + " version=" + getFrameworkVersion());
    }

    @Override
    public void onPackageReady(@NonNull XposedModuleInterface.PackageReadyParam param) {
        String pkg = param.getPackageName();
        if (!"com.android.systemui".equals(pkg)) {
            return;
        }
        log(Log.INFO, TAG, "event=package_ready pkg=" + pkg);

        // Load blocked packages from config file
        blockedPackages = loadBlockedPackages();
        log(Log.INFO, TAG, "event=config_loaded count=" + blockedPackages.size()
                + " packages=" + blockedPackages);

        installHook(param.getClassLoader());
    }

    private synchronized void installHook(ClassLoader classLoader) {
        if (installed) {
            log(Log.INFO, TAG, "event=install_skipped reason=already_installed");
            return;
        }
        try {
            Class<?> actionsKt = classLoader.loadClass(HOOK_TARGET_CLASS);

            // Kotlin top-level function compiles to a static method on the file facade class.
            // createActionsFromState(Context, String, MediaController, UserHandle)
            Method targetMethod = findCreateActionsMethod(actionsKt);
            if (targetMethod == null) {
                log(Log.ERROR, TAG,
                        "event=method_not_found class=" + HOOK_TARGET_CLASS
                                + " method=createActionsFromState");
                return;
            }

            hook(targetMethod)
                    .setId("media_actions_hook")
                    .setExceptionMode(XposedInterface.ExceptionMode.DEFAULT)
                    .intercept(chain -> {
                        // Let original method execute
                        Object result = chain.proceed();

                        try {
                            // args[1] is the packageName (String)
                            Object pkgArg = (chain.getArgs() != null && chain.getArgs().size() > 1)
                                    ? chain.getArgs().get(1)
                                    : null;
                            if (pkgArg == null) {
                                return result;
                            }

                            String packageName = pkgArg.toString();
                            if (!isPackageBlocked(packageName)) {
                                return result;
                            }

                            if (result == null) {
                                return result;
                            }

                            // Get custom0 and custom1 fields via reflection
                            Field fCustom0 = findField(result.getClass(), "custom0");
                            Field fCustom1 = findField(result.getClass(), "custom1");
                            Object custom0 = fCustom0 != null ? fCustom0.get(result) : null;
                            Object custom1 = fCustom1 != null ? fCustom1.get(result) : null;

                            if (custom0 == null && custom1 == null) {
                                return result; // nothing to clear
                            }

                            // Try constructor-based rebuild first (matching bsh reference)
                            Object newBtn = rebuildMediaButton(result);
                            if (newBtn != null) {
                                log(Log.INFO, TAG,
                                        "event=custom_buttons_removed pkg=" + packageName
                                                + " via=constructor");
                                return newBtn;
                            }

                            // Fallback: directly null out custom0/custom1 via reflection
                            if (fCustom0 != null) {
                                fCustom0.setAccessible(true);
                                try {
                                    Field modifiers = Field.class.getDeclaredField("accessFlags");
                                    modifiers.setAccessible(true);
                                    modifiers.setInt(fCustom0,
                                            fCustom0.getModifiers() & ~java.lang.reflect.Modifier.FINAL);
                                } catch (NoSuchFieldException ignored) {
                                }
                                fCustom0.set(result, null);
                            }
                            if (fCustom1 != null) {
                                fCustom1.setAccessible(true);
                                try {
                                    Field modifiers = Field.class.getDeclaredField("accessFlags");
                                    modifiers.setAccessible(true);
                                    modifiers.setInt(fCustom1,
                                            fCustom1.getModifiers() & ~java.lang.reflect.Modifier.FINAL);
                                } catch (NoSuchFieldException ignored) {
                                }
                                fCustom1.set(result, null);
                            }

                            log(Log.INFO, TAG,
                                    "event=custom_buttons_removed pkg=" + packageName
                                            + " via=reflection");

                        } catch (Throwable t) {
                            log(Log.ERROR, TAG, "event=hook_error", t);
                        }

                        return result;
                    });

            installed = true;
            log(Log.INFO, TAG, "event=hook_registered method=" + targetMethod);
        } catch (ClassNotFoundException e) {
            log(Log.WARN, TAG, "event=class_not_found", e);
        } catch (Throwable t) {
            log(Log.ERROR, TAG, "event=install_failed", t);
        }
    }

    /**
     * Check if a package is in the blocked list.
     */
    private boolean isPackageBlocked(String packageName) {
        List<String> list = blockedPackages;
        if (list == null || list.isEmpty()) {
            return false;
        }
        return list.contains(packageName);
    }

    /**
     * Load blocked packages from config file.
     * Falls back to default if file not found.
     */
    private List<String> loadBlockedPackages() {
        List<String> packages = new ArrayList<>();

        File file = new File(CONFIG_FILE);
        if (file.exists() && file.canRead()) {
            try (BufferedReader reader = new BufferedReader(new FileReader(file))) {
                String line;
                while ((line = reader.readLine()) != null) {
                    String trimmed = line.trim();
                    if (!trimmed.isEmpty()) {
                        packages.add(trimmed);
                    }
                }
            } catch (Exception e) {
                log(Log.WARN, TAG, "event=config_read_error path=" + CONFIG_FILE, e);
            }
        } else {
            log(Log.WARN, TAG, "event=config_not_found path=" + CONFIG_FILE
                    + " exists=" + file.exists());
        }

        // Always include defaults if list is empty
        if (packages.isEmpty()) {
            for (String defaultPkg : DEFAULT_PACKAGES) {
                packages.add(defaultPkg);
            }
        }

        return packages;
    }

    /**
     * Try to find createActionsFromState method.
     */
    private static Method findCreateActionsMethod(Class<?> clazz) {
        for (Method m : clazz.getDeclaredMethods()) {
            if ("createActionsFromState".equals(m.getName())) {
                return m;
            }
        }
        return null;
    }

    /**
     * Find a field by name in the class hierarchy.
     */
    private static Field findField(Class<?> clazz, String name) {
        Class<?> c = clazz;
        while (c != null) {
            try {
                Field f = c.getDeclaredField(name);
                f.setAccessible(true);
                return f;
            } catch (NoSuchFieldException e) {
                c = c.getSuperclass();
            }
        }
        return null;
    }

    /**
     * Rebuild MediaButton via constructor, clearing custom0/custom1.
     * Matches the bsh reference: new MediaButton(playOrPause, nextOrCustom, prevOrCustom, null, null, reserveNext, reservePrev)
     *
     * @return new MediaButton instance, or null if constructor not found
     */
    private static Object rebuildMediaButton(Object originalBtn) {
        try {
            Class<?> btnClass = originalBtn.getClass();

            Field fPlayOrPause = findField(btnClass, "playOrPause");
            Field fNextOrCustom = findField(btnClass, "nextOrCustom");
            Field fPrevOrCustom = findField(btnClass, "prevOrCustom");
            Field fReserveNext = findField(btnClass, "reserveNext");
            Field fReservePrev = findField(btnClass, "reservePrev");

            Object playOrPause = fPlayOrPause != null ? fPlayOrPause.get(originalBtn) : null;
            Object nextOrCustom = fNextOrCustom != null ? fNextOrCustom.get(originalBtn) : null;
            Object prevOrCustom = fPrevOrCustom != null ? fPrevOrCustom.get(originalBtn) : null;
            Object reserveNext = fReserveNext != null ? fReserveNext.get(originalBtn) : null;
            Object reservePrev = fReservePrev != null ? fReservePrev.get(originalBtn) : null;

            // Find the 7-arg constructor
            for (Constructor<?> ctor : btnClass.getDeclaredConstructors()) {
                if (ctor.getParameterCount() == 7) {
                    ctor.setAccessible(true);
                    return ctor.newInstance(
                            playOrPause, nextOrCustom, prevOrCustom,
                            null, null,  // custom0 = null, custom1 = null
                            reserveNext, reservePrev
                    );
                }
            }
        } catch (Throwable t) {
            Log.w(TAG, "event=rebuild_failed", t);
        }
        return null;
    }
}
