package com.ham.music_buttomBlock;

import androidx.annotation.NonNull;

import java.lang.reflect.Constructor;
import java.lang.reflect.Field;
import java.lang.reflect.Method;

import io.github.libxposed.api.XposedInterface;
import io.github.libxposed.api.XposedModule;
import io.github.libxposed.api.XposedModuleInterface;

/**
 * LSPosed module: disable custom media buttons (custom0/custom1)
 * in MIUI/HyperOS SystemUI notification bar / media island controls.
 *
 * <p>MIUI SystemUI media controls have 5 button slots:
 * action0=custom0, action1=prev, action2=play/pause, action3=next, action4=custom1.
 * custom0/custom1 come from MediaSession PlaybackState.getCustomActions(),
 * generated by MediaActionsKt.createActionsFromState().
 *
 * <p>This module hooks createActionsFromState and, when the package is in the
 * blocked list, clears the two custom buttons so they do not appear.
 */
public final class ModuleMain extends XposedModule {
    private static final String HOOK_TARGET_CLASS =
            "com.android.systemui.media.controls.domain.pipeline.MediaActionsKt";

    private static final String[] BLOCKED_PACKAGES = {
            "com.netease.cloudmusic",
            "com.tencent.qqmusic"
    };

    private volatile boolean installed;

    public ModuleMain() {
        super();
    }

    @Override
    public void onModuleLoaded(@NonNull XposedModuleInterface.ModuleLoadedParam param) {
    }

    @Override
    public void onPackageReady(@NonNull XposedModuleInterface.PackageReadyParam param) {
        if (!"com.android.systemui".equals(param.getPackageName())) {
            return;
        }
        installHook(param.getClassLoader());
    }

    private synchronized void installHook(ClassLoader classLoader) {
        if (installed) {
            return;
        }
        try {
            Class<?> actionsKt = classLoader.loadClass(HOOK_TARGET_CLASS);

            // Kotlin top-level function compiles to a static method on the file facade class.
            // createActionsFromState(Context, String, MediaController, UserHandle)
            Method targetMethod = findCreateActionsMethod(actionsKt);
            if (targetMethod == null) {
                return;
            }

            hook(targetMethod)
                    .setId("media_actions_hook")
                    .setExceptionMode(XposedInterface.ExceptionMode.DEFAULT)
                    .intercept(chain -> {
                        // Let original method execute
                        Object result = chain.proceed();

                        try {
                            // args[1] is the packageName (String)
                            Object pkgArg = (chain.getArgs() != null && chain.getArgs().size() > 1)
                                    ? chain.getArgs().get(1)
                                    : null;
                            if (pkgArg == null) {
                                return result;
                            }

                            String packageName = pkgArg.toString();
                            if (!isBlocked(packageName)) {
                                return result;
                            }

                            if (result == null) {
                                return result;
                            }

                            // Get custom0 and custom1 fields via reflection
                            Field fCustom0 = findField(result.getClass(), "custom0");
                            Field fCustom1 = findField(result.getClass(), "custom1");
                            Object custom0 = fCustom0 != null ? fCustom0.get(result) : null;
                            Object custom1 = fCustom1 != null ? fCustom1.get(result) : null;

                            if (custom0 == null && custom1 == null) {
                                return result; // nothing to clear
                            }

                            // Try constructor-based rebuild first
                            Object newBtn = rebuildMediaButton(result);
                            if (newBtn != null) {
                                return newBtn;
                            }

                            // Fallback: directly null out custom0/custom1 via reflection
                            if (fCustom0 != null) {
                                setFinalField(fCustom0, result, null);
                            }
                            if (fCustom1 != null) {
                                setFinalField(fCustom1, result, null);
                            }
                        } catch (Throwable ignored) {
                        }

                        return result;
                    });

            installed = true;
        } catch (ClassNotFoundException ignored) {
        } catch (Throwable ignored) {
        }
    }

    private static boolean isBlocked(String packageName) {
        for (String pkg : BLOCKED_PACKAGES) {
            if (pkg.equals(packageName)) {
                return true;
            }
        }
        return false;
    }

    private static Method findCreateActionsMethod(Class<?> clazz) {
        for (Method m : clazz.getDeclaredMethods()) {
            if ("createActionsFromState".equals(m.getName())) {
                return m;
            }
        }
        return null;
    }

    private static Field findField(Class<?> clazz, String name) {
        Class<?> c = clazz;
        while (c != null) {
            try {
                Field f = c.getDeclaredField(name);
                f.setAccessible(true);
                return f;
            } catch (NoSuchFieldException e) {
                c = c.getSuperclass();
            }
        }
        return null;
    }

    private static void setFinalField(Field field, Object target, Object value) throws Exception {
        field.setAccessible(true);
        try {
            Field modifiers = Field.class.getDeclaredField("accessFlags");
            modifiers.setAccessible(true);
            modifiers.setInt(field, field.getModifiers() & ~java.lang.reflect.Modifier.FINAL);
        } catch (NoSuchFieldException ignored) {
        }
        field.set(target, value);
    }

    private static Object rebuildMediaButton(Object originalBtn) {
        try {
            Class<?> btnClass = originalBtn.getClass();

            Field fPlayOrPause = findField(btnClass, "playOrPause");
            Field fNextOrCustom = findField(btnClass, "nextOrCustom");
            Field fPrevOrCustom = findField(btnClass, "prevOrCustom");
            Field fReserveNext = findField(btnClass, "reserveNext");
            Field fReservePrev = findField(btnClass, "reservePrev");

            Object playOrPause = fPlayOrPause != null ? fPlayOrPause.get(originalBtn) : null;
            Object nextOrCustom = fNextOrCustom != null ? fNextOrCustom.get(originalBtn) : null;
            Object prevOrCustom = fPrevOrCustom != null ? fPrevOrCustom.get(originalBtn) : null;
            Object reserveNext = fReserveNext != null ? fReserveNext.get(originalBtn) : null;
            Object reservePrev = fReservePrev != null ? fReservePrev.get(originalBtn) : null;

            // Find the 7-arg constructor
            for (Constructor<?> ctor : btnClass.getDeclaredConstructors()) {
                if (ctor.getParameterCount() == 7) {
                    ctor.setAccessible(true);
                    return ctor.newInstance(
                            playOrPause, nextOrCustom, prevOrCustom,
                            null, null,
                            reserveNext, reservePrev
                    );
                }
            }
        } catch (Throwable ignored) {
        }
        return null;
    }
}
